package org.monarchinitiative.squirls.core;

import org.monarchinitiative.squirls.core.classifier.Classifiable;
import org.monarchinitiative.squirls.core.scoring.Annotatable;

/**
 * Implementors represent containers for variant, predictions generated by splicing analysis, as well as all the
 * associated data.
 */
public interface SplicingPredictionData extends Annotatable, Classifiable {


}
