DELETE FROM SPLICING.SEPTAMERS;
INSERT INTO SPLICING.SEPTAMERS (SEQUENCE, SCORE) VALUES

('AAAAAAA', 0.10),
('AAAAAAC', 0.20),
('AAAAAAG', 0.30),
('AAAAAAT', 0.40),
('AAAAACA', 0.50),
('AAAAACC', 0.60);

