-- HEXAMERS
DROP TABLE IF EXISTS SPLICING.HEXAMERS;

CREATE TABLE SPLICING.HEXAMERS
(
    SEQUENCE CHAR(6) UNIQUE NOT NULL,
    SCORE    DOUBLE         NOT NULL
);


-- SEPTAMERS
DROP TABLE IF EXISTS SPLICING.SEPTAMERS;

CREATE TABLE SPLICING.SEPTAMERS
(
    SEQUENCE CHAR(7) UNIQUE NOT NULL,
    SCORE    DOUBLE         NOT NULL
);
