-- TRANSCRIPTS
DROP TABLE IF EXISTS SPLICING.TRANSCRIPTS;

CREATE TABLE SPLICING.TRANSCRIPTS(
CONTIG VARCHAR(50) NOT NULL,
BEGIN_POS INTEGER NOT NULL,
END_POS INTEGER NOT NULL,
BEGIN_ON_FWD INTEGER NOT NULL,
BEGIN_ON_REV INTEGER NOT NULL,
STRAND BOOLEAN NOT NULL,
TX_ACCESSION VARCHAR(50) NOT NULL,
);

CREATE INDEX TRANSCRIPTS_IDX ON SPLICING.TRANSCRIPTS(CONTIG, BEGIN_POS, END_POS, STRAND);


-- EXONS
DROP TABLE IF EXISTS SPLICING.EXONS;
CREATE TABLE SPLICING.EXONS(
TX_ACCESSION VARCHAR(50) NOT NULL,
BEGIN_POS INTEGER NOT NULL,
END_POS INTEGER NOT NULL
);

CREATE INDEX EXONS_IDX ON SPLICING.EXONS(TX_ACCESSION);


-- INTRONS
DROP TABLE IF EXISTS SPLICING.INTRONS;
CREATE TABLE SPLICING.INTRONS(
TX_ACCESSION VARCHAR(50) NOT NULL,
BEGIN_POS INTEGER NOT NULL,
END_POS INTEGER NOT NULL,
DONOR_SCORE DOUBLE NOT NULL,
ACCEPTOR_SCORE DOUBLE NOT NULL
);

CREATE INDEX INTRONS_IDX ON SPLICING.INTRONS(TX_ACCESSION);