package org.monarchinitiative.squirls.cli.picocmd;

import org.monarchinitiative.squirls.cli.Main;
import org.monarchinitiative.squirls.core.SplicingPredictionData;
import org.springframework.boot.autoconfigure.SpringBootApplication;
import org.springframework.boot.builder.SpringApplicationBuilder;
import org.springframework.context.ConfigurableApplicationContext;
import picocli.CommandLine;

import java.nio.file.Path;
import java.util.Map;
import java.util.concurrent.Callable;
import java.util.stream.Collectors;

@SpringBootApplication
// TODO - consider adding @ParentCommand here or to PicoMain
public abstract class PicoCommand implements Callable<Integer> {

    @CommandLine.Option(names = {"-c", "--config-file"},
            paramLabel = "squirls-config.yml",
            description = "path to configuration file generated by the `generate-config` command")
    public Path configFile;


    protected ConfigurableApplicationContext getContext() {
        // bootstrap Spring application context
        return new SpringApplicationBuilder(Main.class)
                .properties(Map.of("spring.config.location", configFile.toString()))
                .run();
    }

    /**
     * Process predictions for transcripts into a single record in format <code>NM_123456.7=0.88;ENST00000123456.5=0.99</code>
     *
     * @param predictionData map with predictions
     * @return record
     */
    protected static String processScores(Map<String, SplicingPredictionData> predictionData) {
        return predictionData.keySet().stream()
                .sorted()
                .map(tx -> String.format("%s=%f", tx, predictionData.get(tx).getPrediction().getMaxPathogenicity()))
                .collect(Collectors.joining(";"));
    }
}
