DROP TABLE IF EXISTS TRANSCRIPTS;

CREATE TABLE TRANSCRIPTS(
CONTIG VARCHAR(50) NOT NULL,
BEGIN_POS INTEGER NOT NULL,
END_POS INTEGER NOT NULL,
STRAND BOOLEAN NOT NULL
);

CREATE INDEX TRANSCRIPTS_IDX
  ON TRANSCRIPTS(CONTIG, BEGIN_POS, END_POS, STRAND);

