DROP TABLE IF EXISTS EXONS;

CREATE TABLE EXONS(
CONTIG VARCHAR(50) NOT NULL,
BEGIN_POS INTEGER NOT NULL,
END_POS INTEGER NOT NULL,
STRAND BOOLEAN NOT NULL
);

CREATE INDEX EXONS_IDX
  ON EXONS(CONTIG, BEGIN_POS, END_POS, STRAND);

